services:
  #web:
  # FIXME: Blocked on web app ( @Seolin )
  ml:
    image: teamnameunavailable/machine-learning-client:latest.dockerfile_compose_for_mongo_ml
    ports:
      - "80:80"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    