services:
  #web:
  # FIXME: Blocked on web app ( @Seolin )
  ml:
    image: teamnameunavailable/machine-learning-client:latest.dockerfile_compose_for_mongo_ml
    ports:
      - "80:80"
  mongodb:
    build: ./mongodb
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME = ${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD = ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    