name: Build Machine Learning Client

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and tag Docker image
        run: |
            # To reference the latest on a non-trunk branch, use machine-learning-client:latest.branchname
            if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
              docker buildx build --tag ghcr.io/${{ github.repository }}/machine-learning-client:$(date +%s) --tag ghcr.io/${{ github.repository }}/machine-learning-client:${{ github.sha }} --tag ghcr.io/${{ github.repository }}/machine-learning-client:latest --file ./machine-learning-client/Dockerfile .
            else
              docker buildx build --tag ghcr.io/${{ github.repository }}/machine-learning-client:$(date +%s) --tag ghcr.io/${{ github.repository }}/machine-learning-client:${{ github.sha }} --tag ghcr.io/${{ github.repository }}/machine-learning-client:latest.${{ github.ref }} --file ./machine-learning-client/Dockerfile .
            fi

      - name: Log in to GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image to Container Registry
        run: docker push ghcr.io/${{ github.repository }}/machine-learning-client/$(date +%s)
