name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Wait for web image to be built
        uses: lewagon/wait-for-action@v1.3.1
        with:
            ref: ${{ github.ref }}
            